name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry run'
        type: boolean
        required: false
        default: true

permissions:
  contents: write


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci
   #   - run: npx playwright install --with-deps

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: |
          npx tsx tools/scripts/release.ts --dryRun=${{ inputs.dryRun }}

